name: Deploy
on:
  push:
    branches:
      - main

jobs:
  pre_deploy:
    uses: ./.github/workflows/verify_build.yml
  # deploy:
  #   needs: pre_deploy
  #   uses: ./.github/workflows/vercel_deploy.yml
  #   secrets: inherit
