name: Deploy
on:
  push:
    branches:
      - main

jobs:
  pre_deploy:
    uses: ./.github/workflows/verify_build.yml
    secrets: inherit
  deploy:
    needs: pre_deploy
    uses: ./.github/workflows/cloudflare_pages_deploy.yml
    secrets: inherit
